package global

var NormalType = map[string]string{
	"int":       "int32",
	"tinyint":   "int32",
	"smallint":  "int32",
	"mediumint": "int32",
	"enum":      "int32",
	"bigint":    "int64",
	"char":      "string",
	"varchar":   "string",
	"timestamp": "string",
	"date":      "string",
	"time":      "string",
	"datetime":  "string",
	"text":      "string",
	"double":    "double",
	"decimal":   "double",
	"float":     "float",
	"bool":      "bool",
	"binary":    "string",
	"varbinary": "string",
}

var GoType = map[string]string{
	"int":       "google.protobuf.Int32Value",
	"tinyint":   "google.protobuf.Int32Value",
	"smallint":  "google.protobuf.Int32Value",
	"mediumint": "google.protobuf.Int32Value",
	"enum":      "google.protobuf.Int32Value",
	"bigint":    "google.protobuf.Int64Value",
	"char":      "google.protobuf.StringValue",
	"varchar":   "google.protobuf.StringValue",
	"timestamp": "google.protobuf.StringValue",
	"date":      "google.protobuf.StringValue",
	"time":      "google.protobuf.StringValue",
	"datetime":  "google.protobuf.StringValue",
	"text":      "google.protobuf.StringValue",
	"double":    "google.protobuf.DoubleValue",
	"decimal":   "google.protobuf.DoubleValue",
	"float":     "google.protobuf.FloatValue",
	"bool":      "google.protobuf.BoolValue",
	"binary":    "google.protobuf.BoolValue",
	"varbinary": "google.protobuf.BoolValue",
}

var GoGoType = map[string]string{
	"int":       "int32",
	"tinyint":   "int32",
	"smallint":  "int32",
	"mediumint": "int32",
	"enum":      "int32",
	"bigint":    "int64",
	"char":      "string",
	"varchar":   "string",
	"timestamp": "string",
	"date":      "string",
	"time":      "string",
	"datetime":  "string",
	"text":      "string",
	"double":    "double",
	"decimal":   "double",
	"float":     "float",
	"bool":      "bool",
	"binary":    "string",
	"varbinary": "string",
}
