package global

var NormalType = map[string]string{
	"int":       "int32",
	"tinyint":   "int32",
	"smallint":  "int32",
	"mediumint": "int32",
	"enum":      "int32",
	"bigint":    "int64",
	"char":      "string",
	"varchar":   "string",
	"timestamp": "string",
	"date":      "string",
	"time":      "string",
	"datetime":  "string",
	"text":      "string",
	"double":    "double",
	"decimal":   "double",
	"float":     "float32",
	"bool":      "bool",
	"binary":    "string",
	"varbinary": "string",
}

var GoType = map[string]string{
	"int":       "Int32Value",
	"tinyint":   "Int32Value",
	"smallint":  "Int32Value",
	"mediumint": "Int32Value",
	"enum":      "Int32Value",
	"bigint":    "Int64Value",
	"char":      "StringValue",
	"varchar":   "StringValue",
	"timestamp": "StringValue",
	"date":      "StringValue",
	"time":      "StringValue",
	"datetime":  "StringValue",
	"text":      "StringValue",
	"double":    "DoubleValue",
	"decimal":   "DoubleValue",
	"float":     "FloatValue",
	"bool":      "BoolValue",
	"binary":    "StringValue",
	"varbinary": "StringValue",
}

var GoGoType = map[string]string{
	"int":       "int32",
	"tinyint":   "int32",
	"smallint":  "int32",
	"mediumint": "int32",
	"enum":      "int32",
	"bigint":    "int64",
	"char":      "string",
	"varchar":   "string",
	"timestamp": "string",
	"date":      "string",
	"time":      "string",
	"datetime":  "string",
	"text":      "string",
	"double":    "double",
	"decimal":   "double",
	"float":     "float",
	"bool":      "bool",
	"binary":    "string",
	"varbinary": "string",
}
